// GENERATED by mindfulness-content/scripts/course-site.ts — the animated course seasons (botthatlyfe.com/courses/<handle>).
import s0 from "./search-party.mjs";
import s1 from "./the-context-window.mjs";

export const seasons = [s0, s1];
