// GENERATED by mindfulness-content/scripts/course-site.ts — do not hand-edit; re-run npm run course-site -- search-party.
export default {
  "handle": "search-party",
  "title": "Search Party",
  "subtitle": "Faith, AI, and finding your path — Where you at? Where you trying to get to? How you getting there?",
  "course": "Search Party · a Bot That Lyfe study",
  "season": "Season 1",
  "logline": "Three college students in an Agentic AI class are searching for God three different ways — wide, deep, and not at all. Their class teaches graph search; their lives become one. They find out the White Jesus, the Black Jesus and the chakra being Chen meditates with are faces of one Light — teleport their minds to two futures — and bring the good one home. An animated comedy about faith, identity, AI and three questions: Where you at? Where you trying to get to? How you getting there?",
  "audience": "Campus ministries, small groups, Bible studies, youth groups, interfaith councils, and teachers of religion, ethics or AI-and-society — students and young adults 16–30.",
  "outcomes": [
    "Talk honestly about the images of God we inherited — and the Light they point to",
    "Read key passages (John 14:6, Revelation 1:14–15, 1 John 1:5, John 4:24, Acts 17:28) in context",
    "Recognize breadth-first, depth-first and stuck patterns in a spiritual search",
    "Ask of any feed or AI system: what is this optimizing?",
    "Turn a vision into a plan with the three questions — and build something with others"
  ],
  "cast": [
    {
      "name": "Dre",
      "role": "EECS junior · church kid · searches breadth-first"
    },
    {
      "name": "Chen",
      "role": "EECS + cognitive science · meditates · sees the spirit world · searches depth-first"
    },
    {
      "name": "Nia",
      "role": "Religious-studies minor · brings receipts · stuck at the start node"
    },
    {
      "name": "Brent",
      "role": "Lit for Christ worship leader · fog machine enthusiast"
    },
    {
      "name": "Dr. Mei",
      "role": "Teaches EECS 498: Agentic AI · has read the paper"
    },
    {
      "name": "Ms. Lorraine & Pastor Greene",
      "role": "Greater New Light Missionary Baptist · the church family"
    },
    {
      "name": "Jesus (two portrayals)",
      "role": "Dramatized portrayals with original dialogue — kind, funny, the same Light"
    },
    {
      "name": "The Operator",
      "role": "The chakra being · narrator · Chen's guide"
    }
  ],
  "cover": "/assets/courses/search-party/cover.jpg",
  "poster": "/assets/courses/search-party/season-cover.jpg",
  "pdfs": {
    "student": "/assets/courses/search-party/search-party-workbook.pdf",
    "admin": "/assets/courses/search-party/search-party-program-brief.pdf"
  },
  "released": "2026-10-03",
  "page": {
    "titleTag": "Search Party — Faith, AI & Finding Your Path (Free Animated Series) | Bot That Lyfe",
    "description": "Search Party: a free animated comedy about faith, identity and AI. White Jesus, Black Jesus, a chakra guide, a U-M Agentic AI class, two futures — and three questions: where you at, where you trying to get to, how you getting there. Six episodes plus a free viewer study guide with activities.",
    "ogTitle": "Search Party — which Jesus is real? A free animated series about faith and AI",
    "facts": [
      "6 animated episodes",
      "Study guide + activities",
      "Scripture read in context",
      "Group leader guide"
    ],
    "workbookButton": "Free study guide (PDF)",
    "episodesHeading": "Watch in order. Then do the activity.",
    "episodesText": "Each episode asks the same three questions in a new place — a church, a spirit world, a classroom, two futures. Every one comes with an activity, a page to journal, and questions to talk through with your people.",
    "workbookTitle": "Viewer study guide",
    "workbookText": "One page per episode: the big idea, scripture, history and a little science underneath it, words to know, an activity, a journal page, and questions to talk about.",
    "workbookDownload": "Download the study guide (PDF)",
    "briefTitle": "For leaders & groups",
    "briefText": "The group leader guide covers how to run it in six weeks or one retreat, discussion flow, and ideas for checking in.",
    "briefDownload": "Download the leader guide (PDF)",
    "outcomesKicker": "What your group will walk away with",
    "bannerText": "Which Jesus is real? A free animated comedy about faith, AI and finding your path — watch it, then grab the free study guide.",
    "bannerButton": "Watch & get the study guide"
  },
  "og": "/assets/og/season-search-party.jpg",
  "playlistId": "PLe6cqqmeTKuo",
  "playlistUrl": "https://www.youtube.com/playlist?list=PLe6cqqmeTKuo",
  "shortsPlaylistUrl": null,
  "shorts": [],
  "minutes": 32,
  "episodes": [
    {
      "n": 1,
      "title": "Where You At?",
      "youtubeTitle": "White Jesus in a Black Church: Which Jesus Is Real? | Search Party Ep 1",
      "summary": "Dre has prayed under the same blue-eyed Jesus portrait his whole life — and the sermon says nobody gets to the Father except through Him. Nia has receipts from Revelation. Chen meditates into a spirit world where she meets TWO Jesuses. And their Agentic AI class asks the question none of them can answer: where are you at?",
      "big": "You can't find a path from a place you won't admit you're standing in.",
      "learn": [
        "Why the White Jesus on so many church walls is a painting with a history, not a photograph",
        "What John 14:6 and Revelation 1:14–15 actually say — read in context",
        "The three things every agent (and every person) needs: a state, a goal, a path"
      ],
      "videoId": "sEdW2OsAEjI",
      "url": "https://www.youtube.com/watch?v=sEdW2OsAEjI&list=PLe6cqqmeTKuo&index=1",
      "seconds": 358,
      "thumb": "/assets/courses/search-party/ep1.jpg",
      "lessons": [],
      "activity": {
        "title": "Where you at? (the honest map)",
        "steps": [
          "Write the image of God you grew up with — where you saw it, who handed it to you.",
          "Write what you actually believe today, in one plain sentence. No church voice.",
          "Write where you're trying to get — and one small step you could take this week."
        ]
      },
      "journal": "WHERE I'M AT:            ________________________\nWHERE I'M TRYING TO GET: ________________________\nHOW I'M GETTING THERE:   ________________________\nONE STEP THIS WEEK:      ________________________",
      "talk": [
        "What image of Jesus did you grow up with? How did it make you feel?",
        "Dre calls 'only through him' a VIP line. Is that fair? What else could 'the way' mean?",
        "Nia agrees with Dre and still loves her church. Can both be true for you?",
        "Where are you honestly at right now?"
      ]
    },
    {
      "n": 2,
      "title": "Breadth First",
      "youtubeTitle": "I Visited 11 Churches in One Weekend Looking for Jesus | Search Party Ep 2",
      "summary": "Dre goes breadth-first — eleven churches in one weekend: Mass, a fog-machine worship night, a silent Quaker meeting, and an Ethiopian Orthodox chapel where Jesus has looked like his grandmama for centuries. Chen goes depth-first into meditation and loses a whole Tuesday. Nia won't leave the start node. And their AI agent does all three wrong at once.",
      "big": "Wide is how you learn what's out there. Deep is how you learn what's real. And you need to know when to stop.",
      "learn": [
        "Breadth-first vs depth-first search — and which one you're doing with your life",
        "Why Ethiopian Christian art has painted Christ dark-skinned for centuries",
        "What a meditating brain does (theta) — and what binaural-beat science does and doesn't say"
      ],
      "videoId": "ZqZahFhrCpQ",
      "url": "https://www.youtube.com/watch?v=ZqZahFhrCpQ&list=PLe6cqqmeTKuo&index=2",
      "seconds": 307,
      "thumb": "/assets/courses/search-party/ep2.jpg",
      "lessons": [],
      "activity": {
        "title": "Map your search",
        "steps": [
          "List every 'node' you've tried in your search — churches, podcasts, practices, people.",
          "Mark each one: how deep did you actually go? (visited / stayed a while / committed)",
          "Circle the one worth going deeper on, and write your stopping rule for it."
        ]
      },
      "journal": "MY SEARCH STYLE:  wide (BFS) / deep (DFS) / stuck at the start\nGOING DEEPER ON:  ________________________\nI'LL KNOW I'M THERE WHEN: ________________\nI'LL TURN AROUND IF:      ________________",
      "talk": [
        "Are you more Dre (wide), Chen (deep) or Nia (stuck)?",
        "What did the icon chapel teach Dre that eleven parking lots didn't?",
        "What's your stopping rule — for prayer, for study, for scrolling?"
      ]
    },
    {
      "n": 3,
      "title": "Same Light",
      "youtubeTitle": "Black Jesus Meets White Jesus — And They're the Same Light | Search Party Ep 3",
      "summary": "In the spirit world, Dre finally gets to ask Him: why'd you let them paint you like that? Then the White Jesus walks up. Then both of them — and Chen's chakra guide — dissolve into one formless Light. Back in class, Dr. Mei explains patterns on silicon and patterns in carbon, and Dre has a crisis: 'So I'm a chatbot?'",
      "big": "The face is not the point. The Light is.",
      "learn": [
        "What the Bible says God is — light and spirit — beyond any painted face",
        "What most historians agree about the historical Jesus",
        "Brains and neural networks: patterns of electrical activity, in carbon and in silicon"
      ],
      "videoId": "eQHR8O9c5EQ",
      "url": "https://www.youtube.com/watch?v=eQHR8O9c5EQ&list=PLe6cqqmeTKuo&index=3",
      "seconds": 334,
      "thumb": "/assets/courses/search-party/ep3.jpg",
      "lessons": [],
      "activity": {
        "title": "Same Light",
        "steps": [
          "Write down three images of God you've been handed (a painting, a voice, a feeling).",
          "Next to each, write what it points to — what it's trying to show you.",
          "Write one sentence about the Light underneath all three."
        ]
      },
      "journal": "THE IMAGE I WAS HANDED: ________________\nWHAT IT POINTS TO:      ________________\nTHE LIGHT UNDERNEATH:   ________________",
      "talk": [
        "Why do you think both Jesuses said they were 'close'?",
        "Does 'God is light' change how you hear John 14:6?",
        "Dre asks 'So I'm a chatbot?' — what's the difference between a person and a pattern?"
      ]
    },
    {
      "n": 4,
      "title": "Teleport",
      "youtubeTitle": "We Teleported to a Future Where AI Divided Everyone | Search Party Ep 4",
      "summary": "Dre, Chen and Nia use AI-guided meditation to travel into the future — first to Dre's 2016 middle-school cafeteria, then into a branch where feeds sorted everyone into zones by race, church and politics, every zone got its own Jesus, and Chancellor Brent of the Algorithm calls it 'personalization.' Nia names the real problem: it's what we told the machine to optimize.",
      "big": "The future is a graph, and we're choosing the edges right now.",
      "learn": [
        "How engagement-optimized feeds can amplify outrage and division",
        "Why 'what is this optimizing?' is the most important question about any AI system",
        "Futures as a state space: every habit is an edge"
      ],
      "videoId": "Rn5_i-VwqPI",
      "url": "https://www.youtube.com/watch?v=Rn5_i-VwqPI&list=PLe6cqqmeTKuo&index=4",
      "seconds": 316,
      "thumb": "/assets/courses/search-party/ep4.jpg",
      "lessons": [],
      "activity": {
        "title": "Audit your feed",
        "steps": [
          "Scroll your main feed for five minutes. Tally: informed me / connected me / made me mad at someone.",
          "Find one account that makes you mad at a group of people. Ask: what is this optimizing?",
          "Follow one voice from outside your 'zone' for a week. Write what changed."
        ]
      },
      "journal": "WHAT IS THIS OPTIMIZING?  ____________________\nWHO DOES IT SORT ME AWAY FROM?  ______________\nONE EDGE I'LL CHOOSE DIFFERENTLY: ____________",
      "talk": [
        "Brent says they 'personalized' instead of 'sorted.' What's the difference?",
        "'A Black Jesus, not a Black-only Jesus.' What did Dre mean?",
        "Which of your daily habits are edges toward the red branch?"
      ]
    },
    {
      "n": 5,
      "title": "The Jetsons Branch",
      "youtubeTitle": "The Future Where AI Brings Us Together (The Jetsons Branch) | Search Party Ep 5",
      "summary": "This time they go in with a heuristic: does this bring people closer together? The gold branch is the Jetsons — kids learn to breathe before they code, farms on towers, a river you can drink, and an enlightened Future Brent. They bring it home: a campus election against 'Free Fog Machines For All' — and a ten-million-dollar grant.",
      "big": "Pick a heuristic — does this bring people closer? — and let it choose your next step.",
      "learn": [
        "A search: how far you've come plus a good guess of how far is left",
        "What research says about meditation and stress",
        "How a vision becomes a proposal: the three questions as a plan"
      ],
      "videoId": "SJXFTUIWRTE",
      "url": "https://www.youtube.com/watch?v=SJXFTUIWRTE&list=PLe6cqqmeTKuo&index=5",
      "seconds": 304,
      "thumb": "/assets/courses/search-party/ep5.jpg",
      "lessons": [],
      "activity": {
        "title": "Write a Harmony proposal",
        "steps": [
          "Pick one problem on your campus or block (stress, food, a dirty creek, a divided group).",
          "Answer: where are we at, where are we trying to get, how will we get there?",
          "Test every step with the heuristic: does this bring people closer together?"
        ]
      },
      "journal": "PROBLEM:        ____________________\nWHERE WE'RE AT: ____________________\nWHERE TO:       ____________________\nHOW:            ____________________\nHEURISTIC CHECK: does it bring people closer? yes / no",
      "talk": [
        "Future Brent learned the difference between atmosphere and presence. What is it?",
        "What would 'the gold branch' look like on your campus?",
        "Brent wanted to vote for his opponent. When has someone else's vision been better than yours?"
      ]
    },
    {
      "n": 6,
      "title": "Light Speed",
      "youtubeTitle": "3 College Students Win the Nobel Prize With AI and Meditation | Search Party Ep 6",
      "summary": "The season finale. They have to actually build the Harmony Stack — stress bands, a campus farm, river drones, empathy VR — and Dre's 'make it good' prompt blows up the demo. Ms. Lorraine unveils a new church window. Brent finally gets it. And in Stockholm: Physics, Peace... and Mathematics. 'There's no Nobel in math.' 'There is now.'",
      "big": "Know where you're at, name where you're going, choose how — then build it, together.",
      "learn": [
        "How a vision becomes a prototype — and why vague prompts break demos",
        "The whole season's map: breadth, depth, and a good heuristic",
        "Faith and building: the window, the work, the people"
      ],
      "videoId": "Wo9p6PjTIzg",
      "url": "https://www.youtube.com/watch?v=Wo9p6PjTIzg&list=PLe6cqqmeTKuo&index=6",
      "seconds": 321,
      "thumb": "/assets/courses/search-party/ep6.jpg",
      "lessons": [],
      "activity": {
        "title": "Your Harmony Stack",
        "steps": [
          "Pick one thing from the season you want to build — a habit, a project, a group.",
          "Write the three questions for it. Make the goal something you could show someone.",
          "Do the first step in the next 48 hours. Tell someone."
        ]
      },
      "journal": "WHERE YOU AT?            ____________________\nWHERE YOU TRYING TO GET? ____________________\nHOW YOU GETTING THERE?   ____________________\nWHO'S SEARCHING WITH YOU? __________________",
      "talk": [
        "Ms. Lorraine says the new window is 'still Him.' What changed and what didn't?",
        "What was Brent's turn — and what made it real?",
        "What's the first thing you'll build, and who's in your search party?"
      ]
    }
  ]
};
